@startuml
InputView -> CharactorPresenter :キーが押されたことを伝える
CharactorPresenter -> CharactorControl:spaceキーが押された
CharactorPresenter -> CharactorControl:Kキーが押された
CharactorPresenter -> CharactorControl:方向キーが押された
group 状況に応じて
CharactorControl -> CharactorMove
CharactorControl -> CharactorAttack
end

CharactorMove -> CharactorPresenter:動いていることを伝える
' Charactor -> CharactorPresenter
CharactorPresenter <- CharactorAttack:攻撃していることを伝える
CharactorPresenter -> CharactorView:アニメーションを流させる

@enduml